### ISSUE TITLE
link to recount2 in Readme.md is wrong

### ISSUE THREAD

**Issue by lzamparo** [greenelab/multi-plier#34]
I'm going through it now but found a broken link to recount2:

The link as exists in the markdown is : https://http//doi.org/10.1038/nbt.3838, but should be just https://doi.org/10.1038/nbt.3838

Great paper, and thanks for making all aspects so accessible!

**Comment by jaclyn-taroni** [comment]
Thanks very much @lzamparo! I've filed #35, thanks again!
